### ISSUE TITLE
yamltodb does not recognize indexes on materialized views

### ISSUE THREAD

**Issue by deuscapturus** [perseas/Pyrseas#160]
A index specified in a materlized view will not be created by `yamltodb`.  If the index already exists dbtoyaml will remove it.

However, `dbtoyaml` will succesfully add indexes on materliazed views.

```
  materialized view course_authors_unnested:
    definition: " SELECT DISTINCT courses.id AS course_id,\n    unnest(courses.author_ids)\
      \ AS author_id\n   FROM courses;"
    indexes:
      course_authors_indexed_by_course:
        keys:
        - course_id
    owner: ladmin
    privileges:
    - ladmin:
      - all
    - lapp:
      - truncate
      - insert
      - delete
      - select
      - update
    with_data: true
```

**Comment by jmafc** [comment]
It seems like you have the utility names backwards. The ouput YAML shown above, I assume, was created by `dbtoyaml`?  Further, I'm guessing when you used that output with `yamltodb` instead of generating SQL like `CREATE INDEX course_authors_indexed_by_course ...` it generated `DROP INDEX ...` instead?

**Comment by deuscapturus** [comment]
@jmafc Exactly

**Comment by jmafc** [comment]
This is the same as #82 which, as you may see, was fixed by af5b0564, but only in the master branch. If possible, could you please check your test case against an install from master? You could also apply the two-line change to `pyrseas/dbobject/table.py` from the fix, and verify that it works for you. Please let us know if you think we should merge the fix to the r0.7 branch, so that it may eventually be available in a 0.7.x release (if we do have another maint release).

**Comment by deuscapturus** [comment]
Thank you @jmafc.  I've tried the latest master branch.  This issue is still not resolved.

**Comment by jmafc** [comment]
OK. Can you please look at the test `test_view_index` in `tests/dbobject/test_matview.py` (master branch) and see if you can tell us how it differs from your case? Does your matview depend on some other types/functions (see issues tagged "dependencies" which we're working on for a 0.8 release)? Or perhaps it's that the index was created at the same time as the matview (our case tests index creation *after* a matview is in existence).

**Comment by jmafc** [comment]
I've created the following test YAML file, based on the info in the YAML you provided:
```yaml
extension plpgsql:
  description: PL/pgSQL procedural language
  schema: pg_catalog
  version: '1.0'
schema public:
  description: standard public schema
  materialized view cau:
    definition: |2-
       SELECT DISTINCT ca.cid,
          unnest(ca.aids) AS aid
         FROM ca;
    indexes:
      cab:
        keys:
        - cid
    with_data: true
  table a:
    columns:
    - id:
        not_null: true
        type: integer
    - c2:
        type: text
    primary_key:
      a_pkey:
        columns:
        - id
  table c:
    columns:
    - id:
        not_null: true
        type: integer
    - c2:
        type: text
    primary_key:
      c_pkey:
        columns:
        - id
  table ca:
    columns:
    - cid:
        not_null: true
        type: integer
    - aids:
        not_null: true
        type: integer[]
    foreign_keys:
      ca_cid_fkey:
        columns:
        - cid
        references:
          columns:
          - id
          schema: public
          table: c
    primary_key:
      ca_pkey:
        columns:
        - cid
        - aids
```
I added the extra tables, primary keys to foreign keys to make it more realistic and possibly elicit problems with dependencies. I tested against a PG 9.4.11 database (client is 9.6.2) using Python 3.5.3 (also tried the second test with 2.7.13), in two different ways, *after* creating the `a`, `c` and `ca` tables. First, the matview was created in one pass and the index added in a second pass. Second, both the matview and the index were created in a single pass. I did not encounter any problems in my tests. The tests were done against the Pyrseas master branch, last commit 8297929.

Therefore, I need more info from you, for example, versions of PG/Python, steps taken and errors/result output, and maybe try the test above in your environment.

**Comment by deuscapturus** [comment]
Using the example YAML that you posted I could not get yamltodb to generate an index on the materialized view.  PG is 9.5.6.

I'm on the latest commit of the master branch of Pyrseas
```
[tcowan@ip-192-168-6-39 Pyrseas]$ git branch
* master
[tcowan@ip-192-168-6-39 Pyrseas]$ git log
commit 8297929200b83f80bbb65d71db402578404fce8e
Author: Joe Abbate <jma@freedomcircle.com>
Date:   Mon Mar 27 16:37:27 2017 -0400
```

```
postgres=# create database test;
CREATE DATABASE
postgres=# SELECT version();
 PostgreSQL 9.5.6 on x86_64-redhat-linux-gnu, compiled by gcc (GCC) 6.3.1 20161221 (Red Hat 6.3.1-1), 64-bit
```

```
[tcowan@ip-192-168-6-39 Pyrseas]$ python --version
Python 2.7.13
[tcowan@ip-192-168-6-39 Pyrseas]$ python pyrseas/yamltodb.py -u -U postgres -H localhost -p 5432 test test.yaml 
BEGIN;
REVOKE ALL ON SCHEMA public FROM postgres;

REVOKE ALL ON SCHEMA public FROM PUBLIC;

CREATE TABLE ca (
    cid integer NOT NULL,
    aids integer[] NOT NULL);

CREATE TABLE c (
    id integer NOT NULL,
    c2 text);

CREATE TABLE a (
    id integer NOT NULL,
    c2 text);

CREATE MATERIALIZED VIEW cau AS
    SELECT DISTINCT ca.cid,
    unnest(ca.aids) AS aid
   FROM ca;

ALTER TABLE a ADD CONSTRAINT a_pkey PRIMARY KEY (id);

ALTER TABLE c ADD CONSTRAINT c_pkey PRIMARY KEY (id);

ALTER TABLE ca ADD CONSTRAINT ca_pkey PRIMARY KEY (cid, aids);

ALTER TABLE ca ADD CONSTRAINT ca_cid_fkey FOREIGN KEY (cid) REFERENCES c (id);

COMMIT;
Changes applied
[tcowan@ip-192-168-6-39 Pyrseas]$ python pyrseas/yamltodb.py -u -U postgres -H localhost -p 5432 test test.yaml 
```


I tried the same thing on PG 9.4
```
postgres=# create database test;
CREATE DATABASE
postgres=# select version();
                                                    version                                                    
---------------------------------------------------------------------------------------------------------------
 PostgreSQL 9.4.11 on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.3.1 20161221 (Red Hat 6.3.1-1), 64-bit
(1 row)
```

```
[tcowan@tcowan-laptop Pyrseas]$ python pyrseas/yamltodb.py -u -U postgres -H localhost -p 5432 test test.yaml 
BEGIN;
REVOKE ALL ON SCHEMA public FROM postgres;

REVOKE ALL ON SCHEMA public FROM PUBLIC;

CREATE TABLE ca (
    cid integer NOT NULL,
    aids integer[] NOT NULL);

CREATE TABLE c (
    id integer NOT NULL,
    c2 text);

CREATE TABLE a (
    id integer NOT NULL,
    c2 text);

CREATE MATERIALIZED VIEW cau AS
    SELECT DISTINCT ca.cid,
    unnest(ca.aids) AS aid
   FROM ca;

ALTER TABLE a ADD CONSTRAINT a_pkey PRIMARY KEY (id);

ALTER TABLE c ADD CONSTRAINT c_pkey PRIMARY KEY (id);

ALTER TABLE ca ADD CONSTRAINT ca_pkey PRIMARY KEY (cid, aids);

ALTER TABLE ca ADD CONSTRAINT ca_cid_fkey FOREIGN KEY (cid) REFERENCES c (id);

COMMIT;
Changes applied
[tcowan@tcowan-laptop Pyrseas]$ python pyrseas/yamltodb.py -u -U postgres -H localhost -p 5432 test test.yaml 
```

**Comment by jmafc** [comment]
There's a possibility, because Python is sometimes treacherous, that although you're executing from the path of the master branch, your PYTHONPATH is still pointing at your installed Pyrseas 0.7.x. You may want to `echo $PYTHONPATH` and also (from the python prompt) `import sys; sys.path` and look to see if you don't have something like `/usr/local/lib/python2.7/dist-packages` that may be where your Pyrseas 0.7.x is located. I was able to reproduce your output by essentially doing that.

**Comment by deuscapturus** [comment]
@jmafc thank you for your patience, you were correct.  I removed pyrseas from pip and build and installed it from the repo.  Here is my new output.

I recommend a release of Pyrseas with the fix in it 👍   Thank you!

```
REVOKE ALL ON SCHEMA public FROM postgres;

REVOKE ALL ON SCHEMA public FROM PUBLIC;

CREATE TABLE ca (
    cid integer NOT NULL,
    aids integer[] NOT NULL);

CREATE TABLE c (
    id integer NOT NULL,
    c2 text);

CREATE TABLE a (
    id integer NOT NULL,
    c2 text);

CREATE MATERIALIZED VIEW cau AS
    SELECT DISTINCT ca.cid,
    unnest(ca.aids) AS aid
   FROM ca;

ALTER TABLE a ADD CONSTRAINT a_pkey PRIMARY KEY (id);

ALTER TABLE c ADD CONSTRAINT c_pkey PRIMARY KEY (id);

ALTER TABLE ca ADD CONSTRAINT ca_pkey PRIMARY KEY (cid, aids);

ALTER TABLE ca ADD CONSTRAINT ca_cid_fkey FOREIGN KEY (cid) REFERENCES c (id);

CREATE INDEX cab ON cau (cid);
```

**Comment by jmafc** [comment]
Ok, will consider your request. Currently the r0.7 branch only has two unreleased fixes (this, if merged, would be a third). But we're also getting close to fixing issues that may lead to Pyrseas 0.8.

**Comment by Sergey778** [comment]
Hi! When will be release with this issue fix available?

**Comment by jmafc** [comment]
The fix has been merged into master (see c3d8631), so most likely it will have to wait until 0.8. I was hoping to get that done around the time that PG 10 gets released, but we're still cleaning up from the major refactoring done for 0.8 so it may take a while (like, maybe three months if I had to hazard a guess).

@rhunwicks How are you dealing with this? Would you prefer a formal maintenance release, i.e., 0.7.3?

**Comment by Sergey778** [comment]
Thank you for answer! I will try to use Pyrseas from master-branch for my application. Is it stable enough?

**Comment by jmafc** [comment]
It passes our test suite, over 600 tests, against ten Py/PG combinations, and we try to keep it that way, so I'd say, it's stable.
